[

{"@id": "http://docs.oasis-open.org/tac/ns/stix-cve#CVE-2020-36387", "@type": ["http://www.w3.org/2002/07/owl#NamedIndividual", "http://docs.oasis-open.org/cti/ns/stix#Vulnerability"], "http://docs.oasis-open.org/cti/ns/stix/core#description": [{"@value": "An issue was discovered in the Linux kernel before 5.8.2. fs/io_uring.c has a use-after-free related to io_async_task_func and ctx reference holding, aka CID-6d816e088c35."}], "http://docs.oasis-open.org/cti/ns/stix/core#modified": [{"@value": "2021-06-08T00:39:47.252725Z"}], "http://docs.oasis-open.org/cti/ns/stix/core#created": [{"@value": "2021-06-08T00:39:47.252725Z"}], "http://docs.oasis-open.org/cti/ns/stix/core#spec_version": [{"@value": "2.1"}], "http://docs.oasis-open.org/cti/ns/stix/core#id": [{"@value": "vulnerability--0c9ebbed-e46f-4873-9b71-63592f98f0a3"}], "http://docs.oasis-open.org/cti/ns/stix/core#name": [{"@value": "CVE-2020-36387"}], "http://docs.oasis-open.org/cti/ns/stix/core#created_by_ref": [{"@id": "http://docs.oasis-open.org/tac/ns/stix-cve#identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a"}], "http://docs.oasis-open.org/cti/ns/stix/marking#object_marking_refs": [{"@id": "http://docs.oasis-open.org/tac/ns/stix-cve#marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"}]}

]